### ISSUE TITLE
How can i get mission id to add new answers to missions.js ?

### ISSUE THREAD

**Issue by slauter77** [Widiskel/tapswap-bot#1]
Hi there ! I have bunch of answers in list. How can I id missions/answers in your format?

list of answers:
answer - description

739002 - Watch The First Video
5 - Watch New Video
548719 - Learn What The TON Is
030072 - Watch The First Token
Просто посмотреть видео - TapSwap Education
739551 - New In The Crypto World
2614907 - Learn 5 Crypto Terms
D57U94 - TapSwap Education - What The Bitcoin Is?
genesis - How You Can Make Money When Crypto Falling?
27F53K9 - Drops and Rises
encryption - 5 Ways to Make Money on Crypto
4D80N74 - Memes and Cryptocurrencies!
TRIBALISM - Get Started in Crypto
ABENOMICS - 8 Warren Buffet Rules
G5D73H2O - Fake News And Real News
3PM71AK03X - Cryptocurrency Worldwide News First Part
delisting - Cryptocurrency Worldwide News Second Part
collateral - Learn 10 New Crypto Terms
L6SE704V81 - Top 10 Crypto Billionaires 2024
fibonacci - HOW cryptocurrency and money actually works
F35K90V3 - Curious Facts. Top 7 Most Expensive NFT
liveness - What is Bitcoin? The SIMPLEST explanation!
5J6OL847G7 - Hot Crypto News: Ethereum ETFs - Can They Outshine Bitcoin? Web3 Boom - 10M Daily Active Wallets
RANSOMWARE - The Most DANGEROUS Crypto Scams You SHOULD Know About
4K7U6E10G7 - TapSwap Education: Can You Earn 1 Bitcoin Per Day? How Bitcoin Mining Work
tardigrade - What are NFTs and Why They Cost Millions?
F9L34V5A - TapSwap AMA Internal: Launch Dates, Token Conversion, Mining, and Future Features
unbanked - How Elon Musk Impact on Crypto
D5784VHPC377 - Financial Face-Off: Bitcoin Custody vs Bank Accounts | TapSwapEducation
infinite - 7 AI Tools That WILL Make You RICH
5SP670KR66 - The Dark Side of Crypto: Top 8 cyber attacks and how to prevent them |TapSwap Education
parachain - Crypto is not real money! Will cryptocurrency REPLACE fiat money?
D772WQ9Z5 - Unlocking the Future: The Power Trio of Blockchain, IoT, and AI! |TapSwap Education
instamine - How to make $1 Million as a TEENAGER (30 Money Tips)
7N008TQ31V- USDT vs. USDC: The Ultimate Stablecoin Showdown! | TapSwap Education
WebSocket - Without this knowledge you WILL NOT MAKE MONEY in crypto! Crypto explanation for BEGINNERS
0TJN63R97A - Crypto Revolution: Pay with Crypto Using Debit Cards | Curious Facts
unstoppable - The Best Crypto Portfolio for 2024! (LAST CHANCE BEFORE BULL RUN)
3KKLF7JO5 - Top 15 Crypto News: What is the hottest?
Onchain - How To Make 10X On Crypto (Last Chance)
547JL6AM7R - Bitcoin integration to the real life
tendermint - EARN ON AIRDROP
Q7P9N3VD - Delicious Crypto news
renewable - 10 Passive Income Ideas
5G36SQ	- 10 Bitcoin Whales
emission - Ethereum Will Be Worth $20,000
27MZ - Top 10 Bitcoin Whales part 2 
5WH71 - Secure Your Crypto
0P6E - Secure Your Crypto Part 2 L3AE7
marlowe - How Blockchain ACTUALLY Work
function - Do This To Become A Millionaire on 2024

**Comment by Widiskel** [comment]
read on the [README](https://github.com/Widiskel/tapswap-bot/blob/master/README.md)
im already provide how
